// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type NewContent struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type NewPost struct {
	User    string      `json:"user"`
	Content *NewContent `json:"content"`
}

type Post struct {
	ID      string   `json:"ID"`
	User    string   `json:"user"`
	Content *Content `json:"content"`
	Date    string   `json:"date"`
}

type UpdatePost struct {
	ID      string      `json:"ID"`
	Content *NewContent `json:"content"`
}
