// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"cesargdd/graph-api/pb/userspb"
)

type AuthResponse struct {
	Token string        `json:"token"`
	User  *userspb.User `json:"user"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewContent struct {
	Tittle string `json:"tittle"`
	Body   string `json:"body"`
	Image  string `json:"image"`
}

type NewPost struct {
	User    string      `json:"user"`
	Content *NewContent `json:"content"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UpdatePost struct {
	ID      string      `json:"id"`
	Content *NewContent `json:"content"`
}
